project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    
website:
  title: "VisualizaR"
  sidebar:
    contents:
      - href: index.qmd
        text: Introducción al curso
      - href: basico.qmd
        text: Fundamentos
      - href: recursos.qmd
        text: Recursos útiles
      - href: gramatica.qmd
        text: Gramática de los gráficos
      - href: tipos.qmd
        text: Tipos de gráfico
      - href: personalizacion.qmd
        text: Apariencia
      - href: interactivo.qmd
        text: Interactividad

        
  page-footer:
    left: "&copy; Copyright 2024, Rodrigo Rodrigues-Silveira"
    
execute:
  warning: false
  message: false
  error: false

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    code-fold: show
  
bibliography: references.bib

editor: source

